/* Autogenerated file. Do not edit manually. */
/* tslint:disable */
/* eslint-disable */

import { Contract, Signer, utils } from "ethers";
import type { Provider } from "@ethersproject/providers";
import type {
  IEquityToken,
  IEquityTokenInterface,
} from "../../../contracts/interfaces/IEquityToken";

const _abi = [
  {
    inputs: [],
    name: "TokenPaused",
    type: "error",
  },
] as const;

export class IEquityToken__factory {
  static readonly abi = _abi;
  static createInterface(): IEquityTokenInterface {
    return new utils.Interface(_abi) as IEquityTokenInterface;
  }
  static connect(
    address: string,
    signerOrProvider: Signer | Provider
  ): IEquityToken {
    return new Contract(address, _abi, signerOrProvider) as IEquityToken;
  }
}
