/* Autogenerated file. Do not edit manually. */
/* tslint:disable */
/* eslint-disable */
export { IEquityToken__factory } from "./IEquityToken__factory";
export { IWhitelist__factory } from "./IWhitelist__factory";
