/* Autogenerated file. Do not edit manually. */
/* tslint:disable */
/* eslint-disable */

import { Contract, Signer, utils } from "ethers";
import type { Provider } from "@ethersproject/providers";
import type {
  CustomSlotInitializable,
  CustomSlotInitializableInterface,
} from "../../../../contracts/accountAbstraction/core/CustomSlotInitializable";

const _abi = [
  {
    inputs: [],
    name: "InvalidInitialization",
    type: "error",
  },
  {
    inputs: [],
    name: "NotInitializing",
    type: "error",
  },
  {
    anonymous: false,
    inputs: [
      {
        indexed: false,
        internalType: "uint64",
        name: "version",
        type: "uint64",
      },
    ],
    name: "Initialized",
    type: "event",
  },
] as const;

export class CustomSlotInitializable__factory {
  static readonly abi = _abi;
  static createInterface(): CustomSlotInitializableInterface {
    return new utils.Interface(_abi) as CustomSlotInitializableInterface;
  }
  static connect(
    address: string,
    signerOrProvider: Signer | Provider
  ): CustomSlotInitializable {
    return new Contract(
      address,
      _abi,
      signerOrProvider
    ) as CustomSlotInitializable;
  }
}
