version: '3.7'

services:
  postgres:
    image: postgres
    environment:
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: postgres
      POSTGRES_DB: postgres

  app:
    build:
      context: .
    ports:
      - 3000:3000
    volumes:
      - .:/app
    depends_on:
      - postgres
    environment:
      DB_PORT: 5432
      DB_HOST: postgres
      DB_USER: postgres
      DB_PASSWORD: postgres
      DB_DATABASE: postgres
      PRIVATE_KEY: 0xa59b7ed25e6e37337def0b6d293d98e11bb3d69c387726447ab6207817dd8019
      ALCHEMY_API_KEY: tfJxDgUFNhBz9itY5h20TKiSyMi6MNgv
      RPC_URL: https://polygon-mumbai.alchemyapi.io/v2/a59b7ed25e6e37337def0b6d293d98e11bb3d69c387726447ab6207817dd8019
      PAYMASTER_ADDRESS: 0x952F672084621d4480b057DA0010D8e1a33B3858
      TOK_ADDRESS: 0x47e70e809371137C9d0eA0624969ba80f5561F35

    command: npm run start:dev
